// Export pages
export '/auth_onboarding/launch/launch_widget.dart' show LaunchWidget;
export '/auth_onboarding/login/login_widget.dart' show LoginWidget;
export '/a_super_admin/dashboard/dashboard_widget.dart' show DashboardWidget;
export '/a_super_admin/new_school_details_s_a/new_school_details_s_a_widget.dart'
    show NewSchoolDetailsSAWidget;
export '/parent/calender_parent/calender_parent_widget.dart'
    show CalenderParentWidget;
export '/notifications/notification_parent/notification_parent_widget.dart'
    show NotificationParentWidget;
export '/parent/timelinedetails/timelinedetails_widget.dart'
    show TimelinedetailsWidget;
export '/parent/parent_profile/parent_profile_widget.dart'
    show ParentProfileWidget;
export '/notifications/notifications_s_a/notifications_s_a_widget.dart'
    show NotificationsSAWidget;
export '/a_super_admin/add_school_manually_s_a/add_school_manually_s_a_widget.dart'
    show AddSchoolManuallySAWidget;
export '/parent/editprofile_parent/editprofile_parent_widget.dart'
    show EditprofileParentWidget;
export '/a_super_admin/search_page_s_a/search_page_s_a_widget.dart'
    show SearchPageSAWidget;
export '/a_super_admin/edit_profile_s_a/edit_profile_s_a_widget.dart'
    show EditProfileSAWidget;
export '/parent/attendence_parent/attendence_parent_widget.dart'
    show AttendenceParentWidget;
export '/teacher/add_teacher_manually_admin/add_teacher_manually_admin_widget.dart'
    show AddTeacherManuallyAdminWidget;
export '/auth_onboarding/change_password/change_password_widget.dart'
    show ChangePasswordWidget;
export '/a_super_admin/existing_school_details_s_a/existing_school_details_s_a_widget.dart'
    show ExistingSchoolDetailsSAWidget;
export '/admin_dashboard/class_view/class_view_widget.dart'
    show ClassViewWidget;
export '/admin_dashboard/class_dashboard/class_dashboard_widget.dart'
    show ClassDashboardWidget;
export '/teacher/teacher_profile/teacher_profile_widget.dart'
    show TeacherProfileWidget;
export '/a_super_admin/add_branch_s_a/add_branch_s_a_widget.dart'
    show AddBranchSAWidget;
export '/admin_dashboard/add_class_admin/add_class_admin_widget.dart'
    show AddClassAdminWidget;
export '/notifications/notification_admin/notification_admin_widget.dart'
    show NotificationAdminWidget;
export '/admin_dashboard/select_students_admin/select_students_admin_widget.dart'
    show SelectStudentsAdminWidget;
export '/teacher/teacher_attendence_history/teacher_attendence_history_widget.dart'
    show TeacherAttendenceHistoryWidget;
export '/teacher_timeline/teacher_timeline_widget.dart'
    show TeacherTimelineWidget;
export '/admin_dashboard/class_attendence/class_attendence_widget.dart'
    show ClassAttendenceWidget;
export '/admin_dashboard/class_attendence_history/class_attendence_history_widget.dart'
    show ClassAttendenceHistoryWidget;
export '/admin_dashboard/mark_attendence/mark_attendence_widget.dart'
    show MarkAttendenceWidget;
export '/admin_dashboard/add_student_manually/add_student_manually_widget.dart'
    show AddStudentManuallyWidget;
export '/confirmationpages/students_addedtoclass/students_addedtoclass_widget.dart'
    show StudentsAddedtoclassWidget;
export '/noticedetails_class/noticedetails_class_widget.dart'
    show NoticedetailsClassWidget;
export '/admin_dashboard/forgot_password/forgot_password_widget.dart'
    show ForgotPasswordWidget;
export '/a_super_admin/edit_school_s_a/edit_school_s_a_widget.dart'
    show EditSchoolSAWidget;
export '/a_super_admin/edit_branch_s_a/edit_branch_s_a_widget.dart'
    show EditBranchSAWidget;
export '/admin_dashboard/add_events_details/add_events_details_widget.dart'
    show AddEventsDetailsWidget;
export '/admin_dashboard/editclassadmin/editclassadmin_widget.dart'
    show EditclassadminWidget;
export '/confirmationpages/attendance_marked/attendance_marked_widget.dart'
    show AttendanceMarkedWidget;
export '/a_super_admin/change_subscription_plan_s_a/change_subscription_plan_s_a_widget.dart'
    show ChangeSubscriptionPlanSAWidget;
export '/admin_dashboard/students_timeline_activities/students_timeline_activities_widget.dart'
    show StudentsTimelineActivitiesWidget;
export '/confirmationpages/teacherdeleted_succesfully/teacherdeleted_succesfully_widget.dart'
    show TeacherdeletedSuccesfullyWidget;
export '/teacher/edit_teacher_admin/edit_teacher_admin_widget.dart'
    show EditTeacherAdminWidget;
export '/confirmationpages/teacherdetailsedited/teacherdetailsedited_widget.dart'
    show TeacherdetailseditedWidget;
export '/teacher/teachers_gallery/teachers_gallery_widget.dart'
    show TeachersGalleryWidget;
export '/admin_dashboard/calender_class/calender_class_widget.dart'
    show CalenderClassWidget;
export '/parent/student_gallery/student_gallery_widget.dart'
    show StudentGalleryWidget;
export '/parent/indivi_image_view/indivi_image_view_widget.dart'
    show IndiviImageViewWidget;
export '/admin_dashboard/add_calender_details/add_calender_details_widget.dart'
    show AddCalenderDetailsWidget;
export '/a_super_admin/subscription/subscription_widget.dart'
    show SubscriptionWidget;
export '/edi_teacher/edi_teacher_widget.dart' show EdiTeacherWidget;
export '/admin_dashboard/search_page_admin/search_page_admin_widget.dart'
    show SearchPageAdminWidget;
export '/notifications/notification_teacher/notification_teacher_widget.dart'
    show NotificationTeacherWidget;
export '/school_added/school_added_widget.dart' show SchoolAddedWidget;
export '/confirmationpages/schoolapproved/schoolapproved_widget.dart'
    show SchoolapprovedWidget;
export '/confirmationpages/schooldeletedsuccessfully/schooldeletedsuccessfully_widget.dart'
    show SchooldeletedsuccessfullyWidget;
export '/confirmationpages/branch_updated/branch_updated_widget.dart'
    show BranchUpdatedWidget;
export '/confirmationpages/school_updated/school_updated_widget.dart'
    show SchoolUpdatedWidget;
export '/confirmationpages/branch_added/branch_added_widget.dart'
    show BranchAddedWidget;
export '/admin_dashboard/attendence_history_teacher/attendence_history_teacher_widget.dart'
    show AttendenceHistoryTeacherWidget;
export '/amount_not_paidd/amount_not_paidd_widget.dart'
    show AmountNotPaiddWidget;
export '/subscriptionended/subscriptionended_widget.dart'
    show SubscriptionendedWidget;
export '/teacher/teacher_timeline_new/teacher_timeline_new_widget.dart'
    show TeacherTimelineNewWidget;
export '/teacher/teacher_notice/teacher_notice_widget.dart'
    show TeacherNoticeWidget;
export '/teacher/teacher_notice_teacher/teacher_notice_teacher_widget.dart'
    show TeacherNoticeTeacherWidget;
export '/parent/calender_list_parent/calender_list_parent_widget.dart'
    show CalenderListParentWidget;
export '/parent/notice_parent/notice_parent_widget.dart'
    show NoticeParentWidget;
export '/admin_dashboard/addnotice_all_schools/addnotice_all_schools_widget.dart'
    show AddnoticeAllSchoolsWidget;
export '/admin_dashboard/school_notice_view/school_notice_view_widget.dart'
    show SchoolNoticeViewWidget;
export '/subscribtioplan/subscribtioplan_widget.dart'
    show SubscribtioplanWidget;
export '/edit_child_parent/edit_child_parent_widget.dart'
    show EditChildParentWidget;
export '/confirmationpages/child_details_updated/child_details_updated_widget.dart'
    show ChildDetailsUpdatedWidget;
export '/admin_dashboard/class_notice_admin_teacher/class_notice_admin_teacher_widget.dart'
    show ClassNoticeAdminTeacherWidget;
export '/admin_dashboard/notification_v_iew/notification_v_iew_widget.dart'
    show NotificationVIewWidget;
export '/admin_dashboard/new_student/new_student_widget.dart'
    show NewStudentWidget;
export '/admin_dashboard/new_student_edit/new_student_edit_widget.dart'
    show NewStudentEditWidget;
export '/teacher/profile_view/profile_view_widget.dart' show ProfileViewWidget;
export '/admin_dashboard/indistudentmainpages/indistudentmainpages_widget.dart'
    show IndistudentmainpagesWidget;
export '/admin_dashboard/indivi_image_view_teacher/indivi_image_view_teacher_widget.dart'
    show IndiviImageViewTeacherWidget;
export '/admin_dashboard/selectedstudents_sadmin/selectedstudents_sadmin_widget.dart'
    show SelectedstudentsSadminWidget;
export '/admin_dashboard/student_draft/student_draft_widget.dart'
    show StudentDraftWidget;
export '/parent/indivi_video_view/indivi_video_view_widget.dart'
    show IndiviVideoViewWidget;
export '/parent/calender_details_parent/calender_details_parent_widget.dart'
    show CalenderDetailsParentWidget;
export '/admin_dashboard/attendance_history_students_card/attendance_history_students_card_widget.dart'
    show AttendanceHistoryStudentsCardWidget;
export '/admin_dashboard/notice_details/notice_details_widget.dart'
    show NoticeDetailsWidget;
export '/admin_dashboard/event_details/event_details_widget.dart'
    show EventDetailsWidget;
export '/auth_onboarding/guest_page/guest_page_widget.dart'
    show GuestPageWidget;
export '/deletepage/deletepage_widget.dart' show DeletepageWidget;
export '/teacher/teacher_image_view/teacher_image_view_widget.dart'
    show TeacherImageViewWidget;
export '/teacher/teacher_video_view/teacher_video_view_widget.dart'
    show TeacherVideoViewWidget;
export '/admin_dashboard/total_student_listss/total_student_listss_widget.dart'
    show TotalStudentListssWidget;
export '/a_super_admin/edit_admin/edit_admin_widget.dart' show EditAdminWidget;
export '/parent/edit_parent/edit_parent_widget.dart' show EditParentWidget;
export '/a_super_admin/add_newadmin/add_newadmin_widget.dart'
    show AddNewadminWidget;
export '/a_super_admin/edit_admin_copy/edit_admin_copy_widget.dart'
    show EditAdminCopyWidget;
export '/app_update/app_update_widget.dart' show AppUpdateWidget;
export '/admin_dashboard/staff_notice_view/staff_notice_view_widget.dart'
    show StaffNoticeViewWidget;
export '/auth_onboarding/request_location/request_location_widget.dart'
    show RequestLocationWidget;
export '/parent/edit_parent_copy/edit_parent_copy_widget.dart'
    show EditParentCopyWidget;
export '/otp_screen/otp_screen_widget.dart' show OtpScreenWidget;
export '/admin_dashboard/edit_class_student/edit_class_student_widget.dart'
    show EditClassStudentWidget;
export '/admin_dashboard/edit_class_student_copy/edit_class_student_copy_widget.dart'
    show EditClassStudentCopyWidget;
export '/admin_dashboard/add_student_manually_copy2/add_student_manually_copy2_widget.dart'
    show AddStudentManuallyCopy2Widget;
export '/parent/eventdetailsparent/eventdetailsparent_widget.dart'
    show EventdetailsparentWidget;
